CREATE TABLE produto (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	loja_id BIGINT NOT NULL,
	nome VARCHAR(255) NOT NULL,
	preco_custo NUMERIC(10,2) CHECK (preco_custo>=0),
	preco_venda NUMERIC(10,2) CHECK (preco_venda>=0) NOT NULL,
	CONSTRAINT fk_produto_loja FOREIGN KEY (loja_id) REFERENCES loja (id)
);	
	
CREATE UNIQUE INDEX uk_produto_loja_nome
	ON produto (loja_id, nome);

